### ISSUE TITLE
删除 StartAndGC 方法

### ISSUE THREAD

**Issue by flycash** [ecodeclub/beego-cache#2]
站在接口设计的角度，应该让接口尽可能小。

那么 StartAndGC 就违背了这个原则。因为它不是所有实现都必须要实现的方法，比如说在 Redis 里面，它自己就支持过期控制，所以并不需要实现这个方法。

这个方法本身是用于类似于本地缓存，或者本地基于文件的缓存。这种时候就是需要实现者自己管理过期时间的。

因此 StartAndGC 是一个意义不明并且没有必要的方法。

你需要：
- 在 Cache 接口中删除 StartAndGC 方法。
- 将各个实现的 StartAndGC 放过去它的初始化方法里面。
- 提供一个新的 Close 方法，用于关闭缓存，允许实现者在这个方法内部释放资源。

**Comment by uzziahlin** [comment]
我看了一下，beego-cache项目下的Cache接口貌似并没有定义StartAndGC方法，反而在beego项目下的client/cache中好像定义了相关的方法。

**Comment by flycash** [comment]
Beego 中的还不能删。我先关了
